_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
episodes:
    value: 100
epsilon:
    value: 0.2
lr:
    value: 0.001
